apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biznext-event-tool
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /bet
        pathType: ImplementationSpecific
        backend:
          service:
            name: biznext-event-tool
            port:
              number: 5000
