apiVersion: apps/v1
kind: Deployment
metadata:
  name: biznext-event-tool
spec:
  selector:
    matchLabels:
      app: biznext-event-tool
  replicas: 1
  template:
    metadata:
      labels:
        app: biznext-event-tool
    spec:
      containers:
      - name: biznext-event-tool
        image: ghcr.io/sloppycoder/biznext-event-tool:0.1.4
        env:
        - name: BOOTSTRAP_SERVERS
          value: host.docker.internal:9092
        ports:
        - containerPort: 5000
        
---
apiVersion: v1
kind: Service
metadata:
  name: biznext-event-tool
spec:
  type: ClusterIP
  selector:
    app: biznext-event-tool
  ports:
    - name: http
      port: 5000