# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruction_status_executor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!instruction_status_executor.proto\x12 th.co.ktb.biznext.channel.common\"\xfa\x06\n\x19InstructionStatusExecutor\x12R\n\x06header\x18\x01 \x01(\x0b\x32\x42.th.co.ktb.biznext.channel.common.InstructionStatusExecutor.Header\x12N\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32@.th.co.ktb.biznext.channel.common.InstructionStatusExecutor.Data\x1a\x97\x01\n\x06Header\x12\x11\n\tuserRefId\x18\x01 \x01(\t\x12\x16\n\x0e\x63orporateRefId\x18\x02 \x01(\t\x12\x15\n\rcorrelationId\x18\x04 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\t\x12\x17\n\x0f\x63reatedDateTime\x18\x06 \x01(\t\x12\x0e\n\x06userId\x18\x07 \x01(\t\x12\x11\n\teventType\x18\x08 \x01(\t\x1a\xe8\x03\n\x04\x44\x61ta\x12\x18\n\x10instructionRefNo\x18\x01 \x01(\t\x12\x17\n\x0finstructionType\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x15\n\rsourceOrderId\x18\x04 \x01(\t\x12\x1b\n\x13subInstructionRefNo\x18\x05 \x01(\t\x12[\n\x06makers\x18\x06 \x03(\x0b\x32K.th.co.ktb.biznext.channel.common.InstructionStatusExecutor.UserInformation\x12^\n\tapprovers\x18\x07 \x03(\x0b\x32K.th.co.ktb.biznext.channel.common.InstructionStatusExecutor.UserInformation\x12^\n\treviewers\x18\x08 \x03(\x0b\x32K.th.co.ktb.biznext.channel.common.InstructionStatusExecutor.UserInformation\x12\"\n\x1asourceApprovalRequestRefId\x18\t \x01(\t\x12(\n sourceEditedApprovalRequestRefId\x18\n \x01(\t\x1a\x34\n\x0fUserInformation\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x11\n\tuserRefId\x18\x02 \x01(\tB#B!InstructionStatusExecutorProtobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instruction_status_executor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B!InstructionStatusExecutorProtobuf'
  _INSTRUCTIONSTATUSEXECUTOR._serialized_start=72
  _INSTRUCTIONSTATUSEXECUTOR._serialized_end=962
  _INSTRUCTIONSTATUSEXECUTOR_HEADER._serialized_start=266
  _INSTRUCTIONSTATUSEXECUTOR_HEADER._serialized_end=417
  _INSTRUCTIONSTATUSEXECUTOR_DATA._serialized_start=420
  _INSTRUCTIONSTATUSEXECUTOR_DATA._serialized_end=908
  _INSTRUCTIONSTATUSEXECUTOR_USERINFORMATION._serialized_start=910
  _INSTRUCTIONSTATUSEXECUTOR_USERINFORMATION._serialized_end=962
# @@protoc_insertion_point(module_scope)
