# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instruction_status_update.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1finstruction_status_update.proto\x12 th.co.ktb.biznext.channel.common\"\xfe\x07\n\x17InstructionStatusUpdate\x12P\n\x06header\x18\x01 \x01(\x0b\x32@.th.co.ktb.biznext.channel.common.InstructionStatusUpdate.Header\x12L\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32>.th.co.ktb.biznext.channel.common.InstructionStatusUpdate.Data\x1at\n\x06Header\x12\x11\n\tuserRefId\x18\x01 \x01(\t\x12\x16\n\x0e\x63orporateRefId\x18\x02 \x01(\t\x12\x15\n\rcorrelationId\x18\x03 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\t\x12\x17\n\x0f\x63reatedDateTime\x18\x05 \x01(\t\x1a\xf9\x04\n\x04\x44\x61ta\x12\x18\n\x10instructionRefNo\x18\x01 \x01(\t\x12\x1b\n\x13subInstructionRefNo\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0blegacyRefNo\x18\x04 \x01(\t\x12\x15\n\rsourceOrderId\x18\x05 \x01(\t\x12\x11\n\terrorCode\x18\x06 \x01(\t\x12(\n numberOfBulkItemExecutionSuccess\x18\x07 \x01(\x05\x12\'\n\x1fnumberOfBulkItemExecutionFailed\x18\x08 \x01(\x05\x12\x1d\n\x15isRecurringInProgress\x18\t \x01(\t\x12\x65\n\x11\x62ulkFailedRecords\x18\n \x03(\x0b\x32J.th.co.ktb.biznext.channel.common.InstructionStatusUpdate.BulkFailedRecord\x12\x1e\n\x16overallRecurringStatus\x18\x0b \x01(\t\x12\x18\n\x10sourceStatusCode\x18\x0c \x01(\t\x12\x0e\n\x06reason\x18\r \x01(\t\x12\x12\n\nreasonNote\x18\x0e \x01(\t\x12\x38\n0overallRecurringNumberOfBulkItemExecutionSuccess\x18\x0f \x01(\x05\x12\x37\n/overallRecurringNumberOfBulkItemExecutionFailed\x18\x10 \x01(\x05\x12\x41\n9overallRecurringNumberOfBulkItemExecutionPartiallySuccess\x18\x11 \x01(\x05\x1aQ\n\x10\x42ulkFailedRecord\x12\x1a\n\x12paymentReferenceNo\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tB!B\x1fInstructionStatusUpdateProtobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instruction_status_update_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\037InstructionStatusUpdateProtobuf'
  _INSTRUCTIONSTATUSUPDATE._serialized_start=70
  _INSTRUCTIONSTATUSUPDATE._serialized_end=1092
  _INSTRUCTIONSTATUSUPDATE_HEADER._serialized_start=257
  _INSTRUCTIONSTATUSUPDATE_HEADER._serialized_end=373
  _INSTRUCTIONSTATUSUPDATE_DATA._serialized_start=376
  _INSTRUCTIONSTATUSUPDATE_DATA._serialized_end=1009
  _INSTRUCTIONSTATUSUPDATE_BULKFAILEDRECORD._serialized_start=1011
  _INSTRUCTIONSTATUSUPDATE_BULKFAILEDRECORD._serialized_end=1092
# @@protoc_insertion_point(module_scope)
