# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_decimal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protobuf_decimal.proto\x12 th.co.ktb.biznext.channel.common\"-\n\x07\x44\x65\x63imal\x12\x13\n\x0bunscaledVal\x18\x01 \x01(\x0c\x12\r\n\x05scale\x18\x02 \x01(\x05\x42\x11\x42\x0f\x44\x65\x63imalProtobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_decimal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\017DecimalProtobuf'
  _DECIMAL._serialized_start=60
  _DECIMAL._serialized_end=105
# @@protoc_insertion_point(module_scope)
