# name: build and publish container image

on: 
   push:
     tags:
       - '0.*'

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: sloppycoder
          DOCKER_PASSWORD: ${{ secrets.USER_TOKEN }}
          DOCKER_REGISTRY_URL: ghcr.io

      - name: Build :tag
        if: success()
        run: docker build -t ghcr.io/${{ github.repository }}:${IMAGE_TAG} .

      - name: Push to docker hub :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ghcr.io/${{ github.repository }}:${IMAGE_TAG} .
