# name: build and publish container image

on: 
   push:
     tags:
       - '0.*'

jobs:
  python-test-and-build-image:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Linting
        if: success()
        run: |
          flake8 --count --show-source --statistics
      
      - name: Unit tests
        run: |
          pytest -v -s

      - name: Login to github registry
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.USER_TOKEN }}
          DOCKER_REGISTRY_URL: ghcr.io

      - name: Build :tag
        if: success()
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

      - name: Push to image registry :tag
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
