name: build and publish container image

on:
  push:
    tags:        
      - 0.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Echo print values
        run: echo $GITHUB_REF_NAME - ${GITHUB_REF_NAME}
        shell: bash

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: sloppycoder
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build container image
        uses: actions-hub/docker@master
        run: docker build -t docker.io/sloppycoder/bn-event-tool:$GITHUB_REF_NAME .

      - name: Push container image
        uses: actions-hub/docker@master
        run: docker push docker.io/sloppycoder/bn-event-tool:$GITHUB_REF_NAME .
