---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: biznext-event-tool-virtual-service
spec:
  gateways:
  - default/dev-gateway
  hosts:
  - ingress-biznext-admin.gtbdev-vayucloud.krungthai
  http:
  - match:
    - uri:
        prefix: /bet
    name: biznext-event-tool
    route:
    - destination:
        host: biznext-event-tool
        port:
          number: 5000
